/* MEDIOUSAO - Perfil del cliente y Mis pedidos */
(function(){
 const KEY='mediousao_customer_orders';
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const statusLabel=s=>({confirmed:'Confirmado',preparing:'Preparando',ready:'Listo para entregar',delivered:'Entregado',cancelled:'Cancelado',canceled:'Cancelado'}[String(s||'').toLowerCase()]||s||'—');
 function refs(){try{return JSON.parse(localStorage.getItem(KEY)||'[]').filter(x=>x?.id&&x?.token)}catch(e){return[]}}
 function ensure(){
  if(!document.getElementById('mediousaoProfileStyle')){let s=document.createElement('style');s.id='mediousaoProfileStyle';s.textContent=`#profile .profile-head{margin-bottom:16px}#profileOrders .order-card{padding:15px;margin:10px 0}#profileOrders .order-meta{display:grid;gap:6px;margin:10px 0}.profile-empty{text-align:center;padding:24px 16px}.profile-cancel-confirm{padding:12px;border:1px solid #ffd0d0;background:#fff7f7;border-radius:12px;margin-top:10px}.profile-actions{display:flex;gap:8px;margin-top:10px}.profile-actions button{flex:1}`;document.head.appendChild(s)}
  if(!document.getElementById('profile')){let sec=document.createElement('section');sec.id='profile';sec.className='screen';sec.innerHTML=`<div class="profile-head"><h1>👤 Perfil</h1><p class="muted">Tu espacio en MEDIOUSAO</p></div><div class="box" style="padding:15px;margin-bottom:14px"><h2 style="margin-top:0">Mis pedidos</h2><p class="muted">Consulta el estado de tus compras realizadas desde este dispositivo.</p><div id="profileOrders"><div class="notice">Cargando pedidos…</div></div></div>`;document.querySelector('main')?.appendChild(sec)}
  ensureNav();
 }
 function ensureNav(){let nav=document.getElementById('mediousaoBottomNav')||document.querySelector('.app>nav');if(!nav)return;let b=nav.querySelector('[data-profile-nav]');if(!b){b=document.createElement('button');b.setAttribute('data-profile-nav','1');b.innerHTML='<span style="font-size:24px">👤</span><br>Perfil';b.onclick=open;nav.appendChild(b)}}
 async function load(){ensure();let box=document.getElementById('profileOrders'),list=refs();if(!box)return;if(!list.length){box.innerHTML='<div class="profile-empty"><div style="font-size:40px">📦</div><b>Aún no tienes pedidos</b><p class="muted">Cuando hagas una compra aparecerá aquí.</p></div>';return}box.innerHTML='<div class="notice">Actualizando tus pedidos…</div>';let out=[];for(const r of list){try{const {data,error}=await client.rpc('mediousao_customer_order',{p_order_id:r.id,p_access_token:r.token});if(!error&&data?.[0])out.push({ref:r,order:data[0]})}catch(e){console.warn(e)}}if(!out.length){box.innerHTML='<div class="profile-empty"><b>No pudimos cargar tus pedidos.</b><p class="muted">Intenta nuevamente en unos segundos.</p><button class="btn" onclick="mediousaoProfileRefresh()">Actualizar</button></div>';return}box.innerHTML=out.map(({ref:r,order:o})=>{let st=String(o.status||'').toLowerCase(),can=!['delivered','entregado','cancelled','canceled','cancelado'].includes(st);return `<div class="box order-card"><div class="row"><b>${esc(o.order_number||r.number)}</b><span class="status-pill">${esc(statusLabel(o.status))}</span></div><div class="order-meta"><span>Total: <b>RD$${Number(o.total||0).toLocaleString()}</b></span><span>${o.fulfillment_method==='pickup'?'🏪 Recoger':'🛵 Delivery'}</span></div>${can?`<p class="muted">Puedes cancelar tu pedido en cualquier momento antes de que sea entregado.</p><button class="btn danger full" onclick="mediousaoAskCancel('${esc(r.id)}')">Cancelar pedido</button><div id="cancel-${esc(r.id)}"></div>`:''}</div>`}).join('')}
 function open(){ensure();if(typeof show==='function')show('profile');document.querySelectorAll('#mediousaoBottomNav button').forEach(x=>x.classList.remove('on'));document.querySelector('[data-profile-nav]')?.classList.add('on');load()}
 window.mediousaoAskCancel=function(id){let r=refs().find(x=>x.id===id),slot=document.getElementById('cancel-'+id);if(!r||!slot)return;slot.innerHTML=`<div class="profile-cancel-confirm"><b>¿Cancelar este pedido?</b><p class="muted">La cantidad comprada volverá al inventario y el producto quedará en Borradores.</p><div class="profile-actions"><button class="btn" onclick="this.closest('.profile-cancel-confirm').remove()">No</button><button class="btn danger" onclick="mediousaoCancelOrder('${esc(id)}')">Sí, cancelar</button></div></div>`}
 window.mediousaoCancelOrder=async function(id){let r=refs().find(x=>x.id===id);if(!r)return;let slot=document.getElementById('cancel-'+id);if(slot)slot.innerHTML='<div class="notice">Cancelando pedido…</div>';const {error}=await client.rpc('mediousao_customer_cancel_order',{p_order_id:r.id,p_access_token:r.token});if(error){if(slot)slot.innerHTML='<div class="error">'+esc(error.message||'No se pudo cancelar el pedido.')+'</div>';return}await load();if(typeof loadProducts==='function')loadProducts()}
 window.mediousaoOpenProfile=open;window.mediousaoProfileRefresh=load;
 function boot(){ensure();setTimeout(ensureNav,700);setInterval(ensureNav,2000)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
