/* MEDIOUSAO UI + CATALOGO + NAV v2026-09-13 */
(function(){
  function removeSearch(){const h=document.querySelector('header');if(h)h.querySelectorAll('#search,.search,input[placeholder*="Buscar" i],input[placeholder*="Tenis" i]').forEach(e=>e.remove())}
  function hideBonao(){document.querySelectorAll('.app>.notice').forEach(e=>{if((e.textContent||'').toLowerCase().includes('servicio disponible exclusivamente en bonao'))e.style.display='none'})}
  function hideCancel(){document.querySelectorAll('button,a,div,section').forEach(e=>{const t=(e.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();if(t==='❌ cancelar reserva'||t==='cancelar reserva'||t.indexOf('cancelar reserva')===0)e.style.display='none'})}
  function addTopCart(){const h=document.querySelector('header');if(!h||document.getElementById('mediousaoTopCart'))return;const b=document.createElement('button');b.id='mediousaoTopCart';b.setAttribute('aria-label','Carrito');b.innerHTML='🛒';b.style.cssText='position:absolute;right:14px;top:12px;border:0;background:transparent;font-size:27px;padding:8px;z-index:20';b.onclick=()=>show('cart');h.style.position='sticky';h.appendChild(b)}
  function cardFixed(p){const photo=p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" loading="lazy">`:icon(p);return `<div class="card"><div class="photo" onclick="detail('${p.id}')">${photo}</div><div class="info"><div class="name">${esc(p.name)}</div><div class="tag">${esc(labelType(p))} · ${esc(labelAudience(p))}</div><div class="tag">${esc(p.category)} · Talla ${esc(p.size)} · ${esc(p.condition)}</div><div class="price">${money(p.price)}</div><button class="btn primary full" onclick="add('${p.id}')">COMPRAR</button></div></div>`}
  window.render=function(){const type=(document.getElementById('typeFilter')||{}).value||'',aud=(document.getElementById('audienceFilter')||{}).value||'',cat=(document.getElementById('categoryFilter')||{}).value||'';const arr=products.filter(p=>(!type||p.item_type===type)&&(!aud||p.audience===aud)&&(!cat||p.category===cat));const count=document.getElementById('countProducts');if(count)count.textContent=products.length+' disponibles';const home=document.getElementById('homeGrid');if(home)home.innerHTML=arr.slice(0,4).map(cardFixed).join('')||"<div class='notice'>No hay productos publicados todavía.</div>";const grid=document.getElementById('grid');if(grid)grid.innerHTML=arr.map(cardFixed).join('')||"<div class='notice'>No encontramos productos.</div>";if(typeof renderCart==='function')renderCart();if(typeof saveCart==='function')saveCart()}
  window.loadProducts=async function(){try{const {data,error}=await client.from('products').select('id,name,category,size,condition,price,stock,image_url,active,available,is_reserved,reserved_until,created_at,item_type,audience,city').eq('active',true).eq('city',SERVICE_CITY).gt('stock',0).order('created_at',{ascending:false});if(error)throw error;products=(data||[]).filter(p=>p.available!==false&&p.is_reserved!==true);render()}catch(e){console.error('MEDIOUSAO catálogo:',e);products=[];render()}}
  function goUpcoming(){show('home');setTimeout(()=>{const el=document.getElementById('upcomingGrid');if(el)el.scrollIntoView({behavior:'smooth',block:'start'})},100)}
  function addProfile(){if(document.getElementById('mediousaoProfile'))return;const s=document.createElement('section');s.id='mediousaoProfile';s.className='screen';s.innerHTML='<div class="hero"><h1>Perfil</h1><p class="muted">Consulta aquí tus datos y pedidos de MEDIOUSAO.</p><div class="notice">🛍️ Tus compras y reservas se gestionan desde MEDIOUSAO.</div></div>';document.querySelector('.app')?.appendChild(s)}
  function addBottomNav(){if(document.getElementById('mediousaoBottomNav'))return;const n=document.createElement('div');n.id='mediousaoBottomNav';n.style.cssText='position:fixed;left:50%;bottom:0;transform:translateX(-50%);width:min(480px,100%);height:78px;padding:8px 6px;background:#fff;border-top:1px solid #e5e5e7;display:grid;grid-template-columns:repeat(4,1fr);z-index:50';n.innerHTML='<button data-go="home">🏠<br><small>Casa</small></button><button data-go="upcoming">🕘<br><small>Próximamente</small></button><button data-go="reserve">📅<br><small>Reserva</small></button><button data-go="profile">👤<br><small>Perfil</small></button>';n.querySelectorAll('button').forEach(b=>{b.style.cssText='border:0;background:transparent;color:#777;font-weight:750;font-size:14px;line-height:1.25;padding:3px';b.onclick=()=>{const g=b.dataset.go;if(g==='upcoming')goUpcoming();else if(g==='profile'){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById('mediousaoProfile').classList.add('active')}else if(g==='reserve'){show('reserve')}else show(g)}});document.body.appendChild(n);const old=document.querySelector('body>.app nav');if(old)old.style.display='none'}
  function clean(){removeSearch();hideBonao();hideCancel();addTopCart();addProfile();addBottomNav();const h=document.querySelector('header');if(h){h.querySelector('.sub')?.style.setProperty('display','none','important');h.querySelector('.brandline')?.style.setProperty('display','none','important')}const hero=document.querySelector('#home .hero');if(hero)hero.style.display='none';const sec=document.querySelector('#home>.section');if(sec)sec.style.display='none';const up=document.querySelector('#home>section:has(#upcomingGrid)');if(up)up.style.display='none';const conn=document.getElementById('connection');if(conn)conn.style.display='none';document.querySelectorAll('#homeGrid,#grid').forEach(g=>{g.style.display='grid';g.style.gridTemplateColumns='repeat(2,minmax(0,1fr))';g.style.gap='13px';g.style.width='100%'})}
  function start(){clean();loadProducts();if(typeof loadUpcoming==='function')loadUpcoming();setTimeout(clean,300);setTimeout(clean,1000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
